// @ts-check
// sidebars.js — KubeEdge documentation sidebar
// Uses autogenerated mode per top-level section, controlled by
// _category_.json files in each directory for labels and ordering.
// This approach is fully compatible with Docusaurus v2/v3.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  documentationSideBar: [
    {
      type: 'category',
      label: 'Welcome',
      collapsed: false,
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'welcome' }],
    },
    {
      type: 'category',
      label: 'User Guide',
      collapsed: false,
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'user-guide' }],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'developer-guide' }],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'concept' }],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'generated-index' },
      items: [
        { type: 'autogenerated', dirName: 'architecture' },
        { type: 'autogenerated', dirName: 'reference' },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'community' }],
    },
  ],
};

module.exports = sidebars;
